version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      SECRET_KEY: "${SECRET_KEY}"

  migrator:
    build: .
    entrypoint: ["./scripts/deployment/init-db.sh"]
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      SECRET_KEY: "${SECRET_KEY}"
      RUN_DB_INIT: "${RUN_DB_INIT:-false}"
